services:

  node:
    build: ./node
    ports:
      - "8080:8080"
    volumes:
      - ./node:/usr/src/app
    links:
      - nginx
    command: bash -c "npm install && node server.js"

    
  nginx:
    build: ./front
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html
